version: '3'

services:
  dashbot:
    image: crpi-wa5knvxxurqyukha.ap-southeast-1.personal.cr.aliyuncs.com/jianonghe/dashbot:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
