name: Build Frontend, Push Server, Deploy

on:
  push:
    branches:
      - dash-bot-production

jobs:

  build-server-push-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Server Docker Image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPO }}:latest -f Dockerfile .
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPO }}:latest

  deploy-server:
    runs-on: ubuntu-latest
    needs: build-server-push-acr
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Code/DashBot
            git checkout dash-bot-production
            git pull origin dash-bot-production
            docker login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_REGISTRY }}
            docker compose pull
            docker compose up -d
