name: Build and Push Docker Image

on:
  workflow_call:
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      ACR_REGISTRY:
        required: true
      ACR_REPO:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPO }}:latest .
          docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPO }}:latest
